# Generated by Django 4.2.7 on 2025-04-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('is_registered', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('client_account', models.CharField(blank=True, max_length=255, null=True)),
                ('client_account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_lots', models.FloatField(default=0)),
                ('volume_mln_usd', models.FloatField(default=0)),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
