name: exness-client-validator
services:
  - name: web
    environment_slug: python
    buildpacks:
      - name: python
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /
      port: 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    env:
      - key: DEBUG
        value: "False"
        scope: RUN_AND_BUILD_TIME
      - key: DJANGO_ALLOWED_HOSTS
        value: ${APP_DOMAIN}
        scope: RUN_AND_BUILD_TIME
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
    routes:
      - path: /
    source_dir: /

databases:
  - name: db
    engine: PG
    production: false
    cluster_name: exness-client-validator-db
    db_name: postgres
    db_user: postgres 